### ISSUE TITLE
SceneViewer stopped working

### ISSUE THREAD

**Issue by FelipeR2U** [google/model-viewer#2756]
### Description

The app keeps crashing when I try to open on `scene-viewer` and when I can send a report the following error is shown:

```
java.lang.NoSuchMethodError: no non-static method "Lcom/google/android/apps/search/sceneviewer/modelviewer/bh;.setButtonVisibility(ILcom/google/android/libraries/ar/sceneviewer/hotspots/HotspotButton$State;)Z"
	at com.google.android.apps.search.sceneviewer.modelviewer.ImpModelView.nInitialize(Native Method)
	at com.google.android.apps.search.sceneviewer.modelviewer.k.a(SourceFile:1)
	at com.google.android.apps.search.sceneviewer.modelviewer.a.e(SourceFile:4)
	at com.google.android.apps.search.sceneviewer.modelviewer.ImpModelView.D(SourceFile:2)
	at com.google.android.apps.search.sceneviewer.modelviewer.bh$b.b(SourceFile:154)
	at com.google.apps.tiktok.dataservice.de.h(SourceFile:20)
	at com.google.apps.tiktok.dataservice.de.a(SourceFile:2)
	at com.google.apps.tiktok.dataservice.cy.run(SourceFile:19)
	at com.google.apps.tiktok.concurrent.al.run(SourceFile:6)
	at com.google.apps.tiktok.tracing.di.run(SourceFile:2)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7551)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
```

#### Live Demo
Opening it here: https://modelviewer.dev/examples/augmentedreality/#sceneViewer

### Version

- model-viewer: v1.8.0

### Browser Affected

- [x] Chrome, version: 93.0.4577.62
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android, version: Android 10; Redmi Note 8 Pro Build/QP1A.190711.020
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [x] SceneViewer, 
- [ ] QuickLook

Also
- Google app: 12.34.13.23.arm64
- Google play services for AR: 1.26.212010323

**Comment by elalish** [comment]
This sounds l like a known issue that rolled out to 0.3% of users before being fixed, so I'm guessing you were just unlucky? @tpsiaki to verify.

**Comment by tpsiaki** [comment]
Correct - this was in a beta & canary build and it has since been fixed. The build with the fix will be rolling out to all users shortly.
